### ISSUE TITLE
Missing data on dailyConditions.php

### ISSUE THREAD

**Issue by aprsandrew** [aprsworld/craneWeb#1]
If there is a gap in the data (maybe no data from 1st of month???), data is not shown from the current month.   For example, there was data from several days in May for the example shown:

![dailyconditions](https://cloud.githubusercontent.com/assets/7646844/7634944/b7741326-fa23-11e4-99d9-0a06ff03364b.png)

**Comment by Cdetviler** [comment]
Fixed with latest commit
