### ISSUE TITLE
Long query time with large MySQL tables.

### ISSUE THREAD

**Issue by aprsandrew** [aprsworld/craneWeb#2]
With some larger tables (> 1 year of data), the website display lags significantly behind the live data, due to long MySQL query times.  Related to queries in json.php  

In my observations, this was up to 30 second lag.  The query under "find total reports for the day" seemed to be a significant contributor (10+ seconds).   Did not thoroughly investigate the remainder of queries after that one.  

Reducing the size of the table (deleting older records) resolved the issue.  (allowing the website to update regularly every 10 seconds as the new data comes in).  

Need to investigate whether there would be a way to optimize the queries for better performance.

**Comment by Cdetviler** [comment]
Jim said that this issue need a bit more of an extensive look with summary tables. We will work on this some time in the future.

**Comment by aprsandrew** [comment]
This should have nothing to do with summary tables, unless we are exporting/deleting daily data from the table.

Even so, (regardless of how we are handling summary tables), it should only be looking at the past 24 hours of data for current conditions, max wind speed over past hour/today, and the 24 hour graph.  It doesn't make sense that the query time should increase as the table gets larger, if it's only looking at the past 24 hours for the current conditions display.  

Possibly another group by dayofyear issue causing trouble when there's data on the same day of the previous year?  (just speculation, have not looked at the SQL query)

This has been an issue in the past when troubleshooting because what the website is displaying can lag far behind what the operator is seeing.  It should be near real time.

**Comment by kb0thn** [comment]
I will investigate and then probably hand off to Charlie to fix. I did not correctly understand the reported issue.

**Comment by aprsandrew** [comment]
Here is an example of a query that could be optimized.  This particular one is on line 48 of json.php

When written out as it would be queried in mysql:
```
mysql> SELECT COUNT(packet_date) AS nPacketsToday FROM rdLoggerCell_R71 WHERE DATE_ADD(packet_date,INTERVAL -6 HOUR) >= LEFT(DATE_ADD(now(),INTERVAL -6 HOUR),10);
+---------------+
| nPacketsToday |
+---------------+
|             0 |
+---------------+
1 row in set (12.95 sec)
```

The reason for doing the query in that manner is to find results since midnight local time.  The reason it takes so long to query is because it needs to load and sort through the entire table for each query.  This would make sense as to why the lag increases, the larger the table is.  Once the table is loaded into RAM, the queries are shorter (seeing around 0.6 seconds return after that).  But that's still not optimal.  Even something as simple as limiting the query to the past 48 hours vastly increases the return time.  For example:

```
mysql> SELECT COUNT(packet_date) AS nPacketsToday FROM rdLoggerCell_R71 WHERE DATE_ADD(packet_date,INTERVAL -6 HOUR) >= LEFT(DATE_ADD(now(),INTERVAL -6 HOUR),10) AND packet_date>DATE_SUB(now(), INTERVAL 48 HOUR);
+---------------+
| nPacketsToday |
+---------------+
|             0 |
+---------------+
1 row in set (0.00 sec)
```

I'm guessing other queries in json.php could be optimized in like manner, such as the ones under the **/* find max today */** section.

**Comment by Cdetviler** [comment]
This seems to be fixed with the latest commit, but I still would like to test various stations to make sure they are all behaving properly. I also need to test out all of the links on the site and various operations to make sure that my relative links did not break anything.
