### ISSUE TITLE
Internal Memory Percent Full 

### ISSUE THREAD

**Issue by aprsandrew** [aprsworld/craneWeb#4]
Would be useful to add in to the "show status" section, a line with the percentage of internal memory that is full.  This data is available in the rdLoggerCellStatus table (dataflashPage).

Maybe have it show up as red/warning if above x percent, or completely full.

Could also maybe also set up a warning on the webpage when memory is close to being full, instructing to download and erase the internal memory.

There are 4096 pages total (numbered 0 through 4095)

Percentage full is calculated by:
Percentage_Full = (dataflashPage/4095)*100

Note that the current firmware versions do not stop "counting" at 4095.  They keep on incrementing the "dataflashPage" counter, even though the data is not being stored.  So values above 4095 are possible, and will need to be accounted for.

To calculate the number of days remaining:
There are 44 lines of data per page of data flash.
There is one line of data every minute, so that's 44 minutes per page.
There are 4096 pages total, so that is 180224 minutes, or approx 125 days, or about 4 months.
So:
Days_Left = ((4095-dataflashPage)*44)/1440

**Comment by kb0thn** [comment]
Please develop a formula to show estimated days remaining and put it in 
this issue.

On 12/18/2015 9:51 AM, Andrew Kurtz wrote:
> Would be useful to add in to the "show status" section, a line with the
> percentage of internal memory that is full. This data is available in
> the rdLoggerCellStatus table (dataflashPage).
>
> Maybe have it show up as red/warning if above x percent, or completely full.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aprsworld/craneWeb/issues/4>.
>


-- 
-James Jefferson Jarvis
APRS World, LLC
+1-507-454-2727
www.aprsworld.com

**Comment by Cdetviler** [comment]
I implemented this metric under the "show status" section as requested.

It will show a percent rounded to the nearest 10th unless the memory is greater than or equal to 100. In that case it will show "memory full" in red text

**Comment by Cdetviler** [comment]
Did not implement whole enhancement. Need days remaining.
