### ISSUE TITLE
Graph Max vs. Average Max

### ISSUE THREAD

**Issue by aprsandrew** [aprsworld/craneWeb#5]
Based on what I see during testing, I believe the graph on the current conditions page is showing average max (gust) for each line, instead of actual max (highest gust) for each line. 

For example, I injected a ~44 MPH test signal during this period:

![screenshot from 2016-01-15 10 41 34](https://cloud.githubusercontent.com/assets/7646844/12358826/c9fa6bfe-bb74-11e5-87b4-2daa517f30b5.png)

But you can't even see the red max line.  It should be showing a max gust of 44 MPH.

**Comment by aprsandrew** [comment]
Believe I found the place in the code where this issue is.  
In:

data/crane/JSONbacklog.php

There are two mysql queries with the following segment:

```
ROUND(AVG(windGust),1) as gust
```

In both locations, this should be changed to:
```
MAX(windGust) as gust
```

**Comment by Cdetviler** [comment]
The latest commit seems to have fixed this. I will have to test with various stations by double checking with mysql.

**Comment by Cdetviler** [comment]
Specifically: we will test by insert a high gust into R1's data and then let it run at a lower speed for a while and see if it is still averaging.
