### ISSUE TITLE
Cabu display screen is now broken

### ISSUE THREAD

**Issue by aprsandrew** [aprsworld/craneWeb#6]
Example:
http://data.aprsworld.com/data/crane/cabu.php?station_id=R71

Believe it is related to the changes made in the headers section.  For example:
```
<script> var station_id = "'.$serial_id.'"; var parent="'.$serial_id.'"; </script>
```
Changed to:
```
<script> var station_id = "'.$station_id.'"; </script>
```
I also see cabu.js replaced with rdLogger.js which probably affects things as well.  

Station_id / parent are important, because the cabu data is based on the A1234 type serial number, instead of the Rxx crane logger serial number.  A Cabu is 'linked' to a parent rdLogger by the 'parent' field in the deviceInfo table, but the cabu itself has an A type serial number.

**Comment by Cdetviler** [comment]
This should be fixed - it is running on the test site:

http://data.aprsworld.com/data/crane2/craneWeb/cabu.php?station_id=R71

**Comment by Cdetviler** [comment]
This is now live and functioning correctly.

**Comment by kb0thn** [comment]
Andrew - do we want this linked into the real website?

On 4/15/2016 11:26 AM, Charlie Detviler wrote:
> This should be fixed - it is running on the test site:
>
> http://data.aprsworld.com/data/crane2/craneWeb/cabu.php?station_id=R71
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/aprsworld/craneWeb/issues/6#issuecomment-210529889>
>


-- 
-James Jefferson Jarvis
APRS World, LLC
+1-507-454-2727
www.aprsworld.com
