### ISSUE TITLE
Make Cabu page available

### ISSUE THREAD

**Issue by aprsandrew** [aprsworld/craneWeb#7]
At some point, we should probably promote the Cabu display page to the main website.  Not all Crane Logger units have Cabu units though, so we should have some sort of logic to detect whether that unit is associated with a Cabu unit.  If the Cabu unit is present, we could have a link or menu item to "View Cabu / In-Cab Conditions".

**Comment by Cdetviler** [comment]
I currently have the cabu page implemented on the developer version of the craneweb site. It only shows up for units that have cabus attached. However, users are able to see the cabu pages for accounts that are set to private. Once I fix that, this should be able to be implemented.

**Comment by Cdetviler** [comment]
I now have the authorization page working for cabu pages.
